language: php

matrix:
  allow_failures:
    - php: 7
  fast_finish: true

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

before_script:
  - composer install -n --dev --prefer-source

script: vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit --coverage-text
